#!/bin/bash

set -ex
uname -a
# curl -sL https://deb.nodesource.com/setup_12.x | -E bash  - 
# apt-get install -y nodejs npm
# 
npm config set prefix $HOME
npm install -g --unsafe-perm node-gyp ijavascript itypescript
ijsinstall --install=global
its --install=global
